'use client'

import { useState } from 'react'
import { Network } from './visualization/network'

type LabelProps = { index: string; children: React.ReactNode }
function SectionLabel({ index, children }: LabelProps) { return <p className="eyebrow"><span>{index}</span>{children}</p> }
function ArrowLink({ children, href = '#contact' }: { children: React.ReactNode; href?: string }) { return <a className="arrow-link" href={href}>{children}<span aria-hidden="true">↗</span></a> }
function Flow({ items }: { items: string[] }) { return <div className="editorial-flow">{items.map((item, i) => <span key={item}><b>{item}</b>{i < items.length - 1 && <i aria-hidden="true">↓</i>}</span>)}</div> }
function Nav() { return <header className="aksos-nav"><a href="#top" className="wordmark" aria-label="AKSOS home"><img src="/aksos-symbol-traced.svg" alt="" />AKSOS<span className="wordmark-dot">.</span></a><nav aria-label="Primary navigation"><a href="#about">About</a><a href="#atis">ATIS</a><a href="#batana">Batana</a><a href="#contact">Contact</a></nav><a className="nav-cta" href="#batana">Join Batana <span aria-hidden="true">↗</span></a></header> }

const atisStages = [{ name: 'Information', text: 'Fragments from documents, records, projects and public sources.' }, { name: 'Evidence', text: 'Relevant pieces become identifiable and traceable.' }, { name: 'Facts', text: 'Specific statements emerge from the evidence.' }, { name: 'Entities', text: 'People, companies, institutions and projects become resolved.' }, { name: 'Relationships', text: 'Entities connect through observable relationships.' }, { name: 'Context', text: 'Relationships gain meaning in their surrounding environment.' }, { name: 'Intelligence', text: 'Patterns become legible enough to support better questions.' }]
const perspectives = { Investor: 'What should I understand before entering this market?', Enterprise: 'Where are the relationships that could affect or expand my business?', Researcher: 'What patterns exist beneath the evidence?' }

function AtisExperience() { const [stage, setStage] = useState(0); return <div className="atis-experience"><div className="stage-list" role="tablist" aria-label="ATIS conceptual stages">{atisStages.map((item, i) => <button key={item.name} className={stage === i ? 'is-selected' : ''} onClick={() => setStage(i)} role="tab" aria-selected={stage === i}><span>{String(i + 1).padStart(2, '0')}</span>{item.name}</button>)}</div><div className="stage-detail"><p className="system-expansion">STAGE // {String(stage + 1).padStart(2, '0')}</p><h3>{atisStages[stage].name}</h3><p>{atisStages[stage].text}</p><Network preset={stage > 4 ? 'intelligence' : stage > 1 ? 'resolved' : 'fragmented'} label={`ATIS ${atisStages[stage].name.toLowerCase()} visualization`} /></div></div> }
function PerspectiveSelector() { const [perspective, setPerspective] = useState<keyof typeof perspectives>('Investor'); return <div className="perspective-layout"><div className="perspective-tabs" role="tablist" aria-label="Perspective selector">{(Object.keys(perspectives) as Array<keyof typeof perspectives>).map(item => <button key={item} className={perspective === item ? 'is-selected' : ''} onClick={() => setPerspective(item)}>{item.toUpperCase()}</button>)}</div><div className="perspective-answer"><p className="system-expansion">LENS // {perspective.toUpperCase()}</p><h3>{perspectives[perspective]}</h3><Network preset="resolved" label={`Same ecosystem viewed through the ${perspective.toLowerCase()} perspective`} /></div></div> }
function RitaDemo() { const [evaluated, setEvaluated] = useState(false); return <div className={`rita-demo ${evaluated ? 'is-evaluated' : ''}`}><div className="rita-copy"><p>Relationships are easy to collect. Meaning is harder to see.</p><button className="arrow-link button-link" onClick={() => setEvaluated(true)}>{evaluated ? 'Coherence evaluated' : 'Evaluate coherence'} <span aria-hidden="true">→</span></button>{evaluated && <p className="rita-status">SYS // COHERENT_PATTERN_DETECTED<br /><strong>MINISTRY → POLICY → PROJECT → ENTERPRISE</strong></p>}</div><Network preset={evaluated ? 'intelligence' : 'fragmented'} label={evaluated ? 'Evaluated network showing a coherent relationship story' : 'Fragmented network with an unresolved relationship story'} /></div> }

export function AksosPage() { return <main id="top" className="aksos-shell"><Nav /><section className="hero section-grid" aria-labelledby="hero-title"><div className="hero-copy"><SectionLabel index="00">An emerging initiative</SectionLabel><h1 id="hero-title">Make the invisible <em>legible.</em></h1><p className="hero-intro">AKSOS is researching and building systems that make complex African ecosystems more visible, understandable and connected.</p><p className="honesty-note">An active hypothesis. The work is still being tested.</p><ArrowLink href="#problem">Explore the question</ArrowLink></div><div className="hero-network"><Network preset="activity" label="A living ecosystem of companies, markets, capital and institutions" /><p className="figure-note">Companies. Institutions. Capital. Projects.<br />An ecosystem already in motion.</p></div></section>
<section id="problem" className="visibility-section"><div className="section-copy"><SectionLabel index="01">The visibility problem</SectionLabel><h2>The information exists. The relationships are harder to <em>see.</em></h2><p>Signals are distributed across organizations, government documents, projects, enterprises, markets, policies, people, capital and reports. Finding the relationships that make them meaningful is harder.</p></div><div className="problem-proof"><Network preset="fragmented" label="Fragmented signals across an ecosystem" /><p className="technical-note">SYS // FRAGMENTED_COVERAGE<br />Information without context is difficult to navigate.</p></div></section>
<section className="personas"><SectionLabel index="02">Who experiences the gap?</SectionLabel><div className="persona-grid"><article><span>INVESTOR</span><h3>What should I understand before entering this market?</h3><p>Enterprises, institutions, capital, infrastructure, policy and relationships.</p></article><article><span>ENTERPRISE</span><h3>Where are the relationships that could affect or expand my business?</h3><p>Partners, suppliers, customers, competitors, projects and institutions.</p></article><article><span>RESEARCHER</span><h3>What relationships and patterns exist beneath the evidence?</h3><p>Entities, facts, historical relationships, policy and structural patterns.</p></article></div></section>
<section className="hypothesis-section"><SectionLabel index="03">The AKSOS hypothesis</SectionLabel><h2>If ecosystems become more <em>visible,</em> they may become easier to understand and participate in.</h2><p>This is a hypothesis being developed and tested — not a proven outcome.</p><Flow items={['SEE', 'CONNECT', 'UNDERSTAND', 'PARTICIPATE']} /></section>
<section id="about" className="origin-section"><div className="section-copy"><SectionLabel index="04">Origin // Tino Makiriyado</SectionLabel><h2>Experience became an <em>observation.</em></h2><p>Work involving complex systems and ecosystem analysis, including experience at CIVA, exposed how fragmented information can become difficult to access and interpret across developing and emerging-market environments.</p><p>That observation became a problem, then a hypothesis: experience → observation → problem → hypothesis → AKSOS.</p></div><div className="origin-aside"><img src="/aksos-symbol-traced.svg" alt="" /><p>CIVA is provenance of the thinking, not an endorsement of AKSOS.</p></div></section>
<section id="atis" className="atis-section"><div className="section-copy"><SectionLabel index="05">System // ATIS</SectionLabel><p className="system-name">ATIS</p><p className="system-expansion">Africa Trade Intelligence System</p><h2>An evolution of <em>meaning.</em></h2><p>ATIS is the intelligence system being researched and built through AKSOS. It is not information alone — it is the progression from evidence to context to intelligence.</p></div><AtisExperience /></section>
<section className="rita-section"><div><SectionLabel index="06">ATIS // RITA</SectionLabel><h2>Not every connection is a <em>story.</em></h2><p>RITA — Relationship Intelligence &amp; Triage Analyst — is a layer within ATIS for coherence evaluation and story formation. It does not invent the structure. It makes an existing pattern inspectable.</p></div><RitaDemo /></section>
<section className="perspective-section"><SectionLabel index="07">Perspective</SectionLabel><div className="perspective-intro"><h2>The ecosystem does not change. The <em>question</em> does.</h2><p>ATIS maps the ecosystem. RITA finds coherence. Perspective determines what becomes meaningful.</p></div><PerspectiveSelector /></section>
<section id="batana" className="batana-section"><div className="section-copy"><SectionLabel index="08">Participation // Batana</SectionLabel><h2>The work is not meant to happen from a <em>distance.</em></h2><p>Batana is the participation and community layer around the initiative. Participate, contribute, discover opportunities, learn, apply and potentially be selected for deeper involvement.</p><ArrowLink>Join Batana</ArrowLink></div><div className="batana-visual"><Network preset="resolved" label="A human network of contributors and participants" /><Flow items={['PARTICIPATE', 'CONTRIBUTE', 'DISCOVER', 'LEARN', 'APPLY']} /></div></section>
<section className="pilot-section"><div className="section-copy"><SectionLabel index="09">Pilot // Zimbabwe</SectionLabel><h2>An idea needs somewhere real to be <em>tested.</em></h2><p>Zimbabwe is the first environment in which AKSOS is investigating whether a deeper intelligence layer can make an ecosystem easier to see and understand.</p><p>The aim is not to assume a result. It is to produce evidence.</p></div><div className="pilot-graph"><Network preset="intelligence" label="Zimbabwe pilot ecosystem represented as institutions, enterprises, projects and relationships" /><Flow items={['ZIMBABWE', 'TEST', 'EVIDENCE', 'LEARN', 'EVALUATE']} /></div></section>
<section id="contact" className="closing"><SectionLabel index="10">The work is underway</SectionLabel><h2>What happens when an ecosystem becomes easier to <em>see?</em></h2><p>AKSOS is still being researched, tested and built. Zimbabwe is the first environment in which the idea is being put to work.</p><div className="closing-actions"><ArrowLink href="#batana">Join Batana</ArrowLink><ArrowLink>Request ATIS access</ArrowLink></div><div className="closing-words">SEE → CONNECT → UNDERSTAND → ACT → BUILD</div></section><footer className="aksos-footer"><span>AKSOS / AN EMERGING INITIATIVE</span><span>© 2026 AKSOS</span><a href="#top">Back to top ↑</a></footer></main> }
export default AksosPage
