'use client'

import { useEffect, useMemo, useRef, useState } from 'react'

type NodeKind = 'company' | 'government' | 'capital' | 'project' | 'market' | 'institution'
type Node = { id: string; label: string; kind: NodeKind; x: number; y: number; r?: number; labelVisible?: boolean; anchor?: boolean }
type Edge = { from: string; to: string; emphasis?: boolean }
export type NetworkPreset = 'activity' | 'fragmented' | 'resolved' | 'intelligence'

const palettes: Record<NodeKind, string> = { company: '#111111', government: '#555555', capital: '#737373', project: '#242424', market: '#8a8a8a', institution: '#b0b0b0' }
const kinds: NodeKind[] = ['company', 'government', 'capital', 'project', 'market', 'institution']

const basePresets: Record<NetworkPreset, { nodes: Node[]; edges: Edge[] }> = {
  activity: { nodes: [{ id: 'a', label: 'COMPANY', kind: 'company', x: 18, y: 27, r: 4, labelVisible: true, anchor: true }, { id: 'b', label: 'CAPITAL', kind: 'capital', x: 35, y: 45, r: 3 }, { id: 'c', label: 'MARKET', kind: 'market', x: 55, y: 21, r: 4, labelVisible: true }, { id: 'd', label: 'PROJECT', kind: 'project', x: 73, y: 36, r: 3 }, { id: 'e', label: 'INSTITUTION', kind: 'institution', x: 86, y: 65, r: 3 }, { id: 'f', label: 'GOVERNMENT', kind: 'government', x: 58, y: 70, r: 4, labelVisible: true }, { id: 'g', label: 'COMPANY', kind: 'company', x: 25, y: 78, r: 3 }, { id: 'h', label: 'MARKET', kind: 'market', x: 8, y: 63, r: 2 }, { id: 'i', label: 'PROJECT', kind: 'project', x: 42, y: 13, r: 2 }, { id: 'j', label: 'CAPITAL', kind: 'capital', x: 80, y: 16, r: 2 }], edges: [{ from: 'a', to: 'b' }, { from: 'b', to: 'c' }, { from: 'c', to: 'd' }, { from: 'd', to: 'e' }, { from: 'e', to: 'f' }, { from: 'f', to: 'g' }, { from: 'g', to: 'h' }, { from: 'h', to: 'a' }, { from: 'a', to: 'i' }, { from: 'c', to: 'i' }, { from: 'c', to: 'j' }, { from: 'd', to: 'j' }, { from: 'b', to: 'g' }, { from: 'f', to: 'd' }] },
  fragmented: { nodes: [{ id: 'a', label: 'COMPANY', kind: 'company', x: 15, y: 25, r: 4, labelVisible: true, anchor: true }, { id: 'b', label: 'REGULATION', kind: 'government', x: 42, y: 16, r: 2 }, { id: 'c', label: 'CAPITAL', kind: 'capital', x: 80, y: 24, r: 4, labelVisible: true }, { id: 'd', label: 'PROJECT', kind: 'project', x: 22, y: 70, r: 4, labelVisible: true }, { id: 'e', label: 'INSTITUTION', kind: 'institution', x: 50, y: 75, r: 3 }, { id: 'f', label: 'MARKET', kind: 'market', x: 83, y: 70, r: 4, labelVisible: true }, { id: 'g', label: 'MINISTRY', kind: 'government', x: 59, y: 39, r: 2 }, { id: 'h', label: 'PERSON', kind: 'institution', x: 8, y: 50, r: 2 }], edges: [{ from: 'a', to: 'b' }, { from: 'c', to: 'g' }, { from: 'd', to: 'e' }, { from: 'e', to: 'f' }, { from: 'h', to: 'd' }] },
  resolved: { nodes: [{ id: 'a', label: 'COMPANY', kind: 'company', x: 19, y: 30, r: 5, labelVisible: true, anchor: true }, { id: 'b', label: 'CAPITAL', kind: 'capital', x: 39, y: 48, r: 3 }, { id: 'c', label: 'GOVERNMENT', kind: 'government', x: 60, y: 26, r: 4, labelVisible: true }, { id: 'd', label: 'PROJECT', kind: 'project', x: 77, y: 48, r: 3 }, { id: 'e', label: 'MARKET', kind: 'market', x: 61, y: 76, r: 4, labelVisible: true }, { id: 'f', label: 'INSTITUTION', kind: 'institution', x: 35, y: 76, r: 3 }, { id: 'g', label: 'REGULATION', kind: 'government', x: 47, y: 18, r: 2 }, { id: 'h', label: 'PERSON', kind: 'institution', x: 12, y: 65, r: 2 }], edges: [{ from: 'a', to: 'b', emphasis: true }, { from: 'a', to: 'c' }, { from: 'a', to: 'h' }, { from: 'b', to: 'c', emphasis: true }, { from: 'b', to: 'd' }, { from: 'b', to: 'f' }, { from: 'c', to: 'd', emphasis: true }, { from: 'c', to: 'g' }, { from: 'd', to: 'e', emphasis: true }, { from: 'e', to: 'f' }, { from: 'f', to: 'a' }, { from: 'g', to: 'b' }] },
  intelligence: { nodes: [{ id: 'a', label: 'AKSOS', kind: 'company', x: 50, y: 50, r: 7, labelVisible: true, anchor: true }, { id: 'b', label: 'COMPANY', kind: 'company', x: 17, y: 23, r: 4, labelVisible: true }, { id: 'c', label: 'CAPITAL', kind: 'capital', x: 79, y: 22, r: 4, labelVisible: true }, { id: 'd', label: 'GOVERNMENT', kind: 'government', x: 84, y: 72, r: 4, labelVisible: true }, { id: 'e', label: 'PROJECT', kind: 'project', x: 50, y: 84, r: 4 }, { id: 'f', label: 'MARKET', kind: 'market', x: 16, y: 73, r: 4, labelVisible: true }, { id: 'g', label: 'INSTITUTION', kind: 'institution', x: 31, y: 47, r: 2 }, { id: 'h', label: 'REGULATION', kind: 'government', x: 69, y: 47, r: 2 }, { id: 'i', label: 'PERSON', kind: 'institution', x: 37, y: 66, r: 2 }, { id: 'j', label: 'MINISTRY', kind: 'government', x: 64, y: 67, r: 2 }], edges: [{ from: 'a', to: 'b', emphasis: true }, { from: 'a', to: 'c', emphasis: true }, { from: 'a', to: 'd', emphasis: true }, { from: 'a', to: 'e', emphasis: true }, { from: 'a', to: 'f', emphasis: true }, { from: 'a', to: 'g' }, { from: 'a', to: 'h' }, { from: 'a', to: 'i' }, { from: 'a', to: 'j' }, { from: 'b', to: 'g' }, { from: 'c', to: 'h' }, { from: 'd', to: 'j' }, { from: 'e', to: 'i' }, { from: 'f', to: 'g' }] },
}

function inAfrica(x: number, y: number) { const upper = 24 + (x < 35 ? x * 0.38 : x < 70 ? 13 : (100 - x) * 0.34); const lower = 84 - Math.max(0, x - 50) * 0.32 - Math.max(0, 25 - x) * 0.08; return y > upper && y < lower && !(x < 12 && y > 63) && !(x > 84 && y < 42) }
function makeNetwork(preset: NetworkPreset) { const base = basePresets[preset]; const extraCount = preset === 'activity' ? 270 : preset === 'intelligence' ? 180 : 120; const extra: Node[] = []; for (let i = 0; i < extraCount; i++) { const x = (i * 47.17 + 13) % 94 + 3; const y = (i * 71.31 + 9) % 82 + 9; if (preset === 'activity' && !inAfrica(x, y)) continue; extra.push({ id: `micro-${i}`, label: 'NODE', kind: kinds[i % kinds.length], x, y, r: i % 23 === 0 ? 2.4 : i % 7 === 0 ? 1.7 : i % 3 === 0 ? 1.2 : 0.85 }) } const nodes = [...base.nodes, ...extra]; const microEdges: Edge[] = extra.map((node, index) => ({ from: node.id, to: nodes[(index * 7 + 3) % base.nodes.length].id })); return { nodes, edges: [...base.edges, ...microEdges] } }

export function Network({ preset, label }: { preset: NetworkPreset; label: string }) { const ref = useRef<SVGSVGElement>(null); const [active, setActive] = useState<string | null>(null); const [visible, setVisible] = useState(false); const [reduced, setReduced] = useState(false); const config = useMemo(() => makeNetwork(preset), [preset]); const positions = useMemo(() => Object.fromEntries(config.nodes.map((n, i) => [n.id, { x: n.x, y: n.y, phase: i * 0.17 }])) as Record<string, { x: number; y: number; phase: number }>, [config])
  useEffect(() => { const media = window.matchMedia('(prefers-reduced-motion: reduce)'); const update = () => setReduced(media.matches); update(); media.addEventListener('change', update); const observer = new IntersectionObserver(([entry]) => setVisible(entry.isIntersecting), { threshold: 0.05 }); if (ref.current) observer.observe(ref.current); return () => { media.removeEventListener('change', update); observer.disconnect() } }, [])
  useEffect(() => { if (reduced || !visible || !ref.current) return; let frame = 0; const start = performance.now(); const tick = (now: number) => { const t = (now - start) / 1000; config.nodes.forEach((node) => { const point = ref.current?.querySelector(`[data-node="${node.id}"]`) as SVGGElement | null; const base = positions[node.id]; if (point && base) point.setAttribute('transform', `translate(${base.x + Math.sin(t * 0.16 + base.phase) * (node.r && node.r > 3 ? 0.22 : 0.42)} ${base.y + Math.cos(t * 0.13 + base.phase) * 0.32})`) }); frame = requestAnimationFrame(tick) }; frame = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame) }, [config, positions, reduced, visible])
  const neighbors = active ? new Set(config.edges.flatMap((edge) => edge.from === active ? [edge.to] : edge.to === active ? [edge.from] : [])) : null
  return <div className="network-frame"><svg ref={ref} className="network-svg" viewBox="0 0 100 100" role="img" aria-label={label} preserveAspectRatio="xMidYMid meet"><g className="network-grid"><path d="M0 25H100M0 50H100M0 75H100M25 0V100M50 0V100M75 0V100" /></g><g className="network-edges">{config.edges.map((edge, i) => { const from = config.nodes.find((n) => n.id === edge.from)!; const to = config.nodes.find((n) => n.id === edge.to)!; const dim = active && active !== edge.from && active !== edge.to && !neighbors?.has(edge.from) && !neighbors?.has(edge.to); return <line key={`${edge.from}-${edge.to}-${i}`} x1={from.x} y1={from.y} x2={to.x} y2={to.y} className={`${edge.emphasis ? 'edge-emphasis' : ''} ${dim ? 'is-dim' : ''}`} /> })}</g>{config.nodes.map((node) => { const isActive = active === node.id; const dim = active && !isActive && !neighbors?.has(node.id); const hasLabel = node.labelVisible; return <g key={node.id} data-node={node.id} transform={`translate(${node.x} ${node.y})`} className={`network-node ${node.anchor ? 'is-anchor' : ''} ${isActive ? 'is-active' : ''} ${dim ? 'is-dim' : ''}`} onMouseEnter={() => setActive(node.id)} onMouseLeave={() => setActive(null)} onFocus={() => setActive(node.id)} onBlur={() => setActive(null)} tabIndex={node.r && node.r > 3 ? 0 : -1} role={node.r && node.r > 3 ? 'button' : undefined} aria-label={node.r && node.r > 3 ? `${node.label} entity` : undefined}><circle r={node.r ?? 1} fill={palettes[node.kind]} />{node.anchor && <circle r={(node.r ?? 1) + 2.4} className="node-ring anchor-ring" />}{hasLabel && <text x={(node.r ?? 4) + 6} y="1" className="node-label">{node.label}</text>}</g> })}</svg><span className="network-caption">{label}</span></div> }
