'use client'

import { useEffect, useMemo, useRef, useState } from 'react'

type NodeKind = 'company' | 'government' | 'capital' | 'project' | 'market' | 'institution'
type GraphNode = { id: string; label: string; kind: NodeKind; x: number; y: number; anchor?: boolean }
type GraphEdge = { from: string; to: string; emphasis?: boolean }
export type NetworkPreset = 'activity' | 'fragmented' | 'resolved' | 'intelligence'

const colors: Record<NodeKind, string> = { company: '#171717', government: '#4d4d4d', capital: '#777', project: '#2e2e2e', market: '#929292', institution: '#b5b5b5' }
const seeds: Record<NetworkPreset, { nodes: GraphNode[]; edges: GraphEdge[] }> = {
  activity: { nodes: [{ id: 'company', label: 'COMPANY', kind: 'company', x: 18, y: 27, anchor: true }, { id: 'capital', label: 'CAPITAL', kind: 'capital', x: 35, y: 45 }, { id: 'market', label: 'MARKET', kind: 'market', x: 55, y: 21, anchor: true }, { id: 'project', label: 'PROJECT', kind: 'project', x: 73, y: 36 }, { id: 'institution', label: 'INSTITUTION', kind: 'institution', x: 86, y: 65 }, { id: 'government', label: 'GOVERNMENT', kind: 'government', x: 58, y: 70, anchor: true }, { id: 'enterprise', label: 'COMPANY', kind: 'company', x: 25, y: 78 }, { id: 'region', label: 'MARKET', kind: 'market', x: 8, y: 63 }], edges: [{ from: 'company', to: 'capital' }, { from: 'capital', to: 'market' }, { from: 'market', to: 'project' }, { from: 'project', to: 'institution' }, { from: 'institution', to: 'government' }, { from: 'government', to: 'enterprise' }, { from: 'enterprise', to: 'region' }, { from: 'region', to: 'company' }] },
  fragmented: { nodes: [{ id: 'company', label: 'COMPANY', kind: 'company', x: 15, y: 25, anchor: true }, { id: 'regulation', label: 'REGULATION', kind: 'government', x: 42, y: 16 }, { id: 'capital', label: 'CAPITAL', kind: 'capital', x: 80, y: 24, anchor: true }, { id: 'project', label: 'PROJECT', kind: 'project', x: 22, y: 70, anchor: true }, { id: 'institution', label: 'INSTITUTION', kind: 'institution', x: 50, y: 75 }, { id: 'market', label: 'MARKET', kind: 'market', x: 83, y: 70, anchor: true }, { id: 'ministry', label: 'MINISTRY', kind: 'government', x: 59, y: 39 }, { id: 'person', label: 'PERSON', kind: 'institution', x: 8, y: 50 }], edges: [{ from: 'company', to: 'regulation' }, { from: 'capital', to: 'ministry' }, { from: 'project', to: 'institution' }, { from: 'institution', to: 'market' }, { from: 'person', to: 'project' }] },
  resolved: { nodes: [{ id: 'company', label: 'COMPANY', kind: 'company', x: 19, y: 30, anchor: true }, { id: 'capital', label: 'CAPITAL', kind: 'capital', x: 39, y: 48 }, { id: 'government', label: 'GOVERNMENT', kind: 'government', x: 60, y: 26, anchor: true }, { id: 'project', label: 'PROJECT', kind: 'project', x: 77, y: 48 }, { id: 'market', label: 'MARKET', kind: 'market', x: 61, y: 76, anchor: true }, { id: 'institution', label: 'INSTITUTION', kind: 'institution', x: 35, y: 76 }, { id: 'regulation', label: 'REGULATION', kind: 'government', x: 47, y: 18 }, { id: 'person', label: 'PERSON', kind: 'institution', x: 12, y: 65 }], edges: [{ from: 'company', to: 'capital', emphasis: true }, { from: 'company', to: 'government' }, { from: 'company', to: 'person' }, { from: 'capital', to: 'government', emphasis: true }, { from: 'capital', to: 'project' }, { from: 'capital', to: 'institution' }, { from: 'government', to: 'project', emphasis: true }, { from: 'government', to: 'regulation' }, { from: 'project', to: 'market', emphasis: true }, { from: 'market', to: 'institution' }, { from: 'institution', to: 'company' }, { from: 'regulation', to: 'capital' }] },
  intelligence: { nodes: [{ id: 'akos', label: 'AKSOS', kind: 'company', x: 50, y: 50, anchor: true }, { id: 'company', label: 'COMPANY', kind: 'company', x: 17, y: 23, anchor: true }, { id: 'capital', label: 'CAPITAL', kind: 'capital', x: 79, y: 22, anchor: true }, { id: 'government', label: 'GOVERNMENT', kind: 'government', x: 84, y: 72, anchor: true }, { id: 'project', label: 'PROJECT', kind: 'project', x: 50, y: 84, anchor: true }, { id: 'market', label: 'MARKET', kind: 'market', x: 16, y: 73, anchor: true }, { id: 'institution', label: 'INSTITUTION', kind: 'institution', x: 31, y: 47 }, { id: 'regulation', label: 'REGULATION', kind: 'government', x: 69, y: 47 }, { id: 'person', label: 'PERSON', kind: 'institution', x: 37, y: 66 }, { id: 'ministry', label: 'MINISTRY', kind: 'government', x: 64, y: 67 }], edges: [{ from: 'akos', to: 'company', emphasis: true }, { from: 'akos', to: 'capital', emphasis: true }, { from: 'akos', to: 'government', emphasis: true }, { from: 'akos', to: 'project', emphasis: true }, { from: 'akos', to: 'market', emphasis: true }, { from: 'akos', to: 'institution' }, { from: 'akos', to: 'regulation' }, { from: 'akos', to: 'person' }, { from: 'akos', to: 'ministry' }, { from: 'company', to: 'institution' }, { from: 'capital', to: 'regulation' }, { from: 'government', to: 'ministry' }, { from: 'project', to: 'person' }, { from: 'market', to: 'institution' }] },
}

function buildGraph(preset: NetworkPreset) { const seed = seeds[preset]; const extras = Array.from({ length: preset === 'activity' ? 104 : 54 }, (_, i) => ({ id: `n${i}`, label: 'NODE', kind: (['company', 'government', 'capital', 'project', 'market', 'institution'] as NodeKind[])[i % 6], x: 4 + ((i * 47.17 + 13) % 92), y: 7 + ((i * 31.31 + 9) % 86) })); return { nodes: [...seed.nodes, ...extras], edges: [...seed.edges, ...extras.map((node, i) => ({ from: node.id, to: seed.nodes[(i * 3 + 1) % seed.nodes.length].id }))] } }

export function Network({ preset, label, interactive = true }: { preset: NetworkPreset; label: string; interactive?: boolean }) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const wrapRef = useRef<HTMLDivElement>(null); const [active, setActive] = useState<string | null>(null); const [reduced, setReduced] = useState(false); const graph = useMemo(() => buildGraph(preset), [preset]);
  useEffect(() => { const media = window.matchMedia('(prefers-reduced-motion: reduce)'); const update = () => setReduced(media.matches); update(); media.addEventListener('change', update); return () => media.removeEventListener('change', update) }, [])
  useEffect(() => { const canvas = canvasRef.current; const wrap = wrapRef.current; if (!canvas || !wrap) return; const ctx = canvas.getContext('2d'); if (!ctx) return; let raf = 0; let start = performance.now(); const resize = () => { const dpr = window.devicePixelRatio || 1; const rect = wrap.getBoundingClientRect(); canvas.width = rect.width * dpr; canvas.height = rect.height * dpr; ctx.setTransform(dpr, 0, 0, dpr, 0, 0) }; const draw = (now: number) => { const rect = wrap.getBoundingClientRect(); const t = reduced ? 0 : (now - start) / 1000; ctx.clearRect(0, 0, rect.width, rect.height); const point = (n: GraphNode) => ({ x: rect.width * n.x / 100 + Math.sin(t * .12 + n.x) * (n.anchor ? .15 : .35), y: rect.height * n.y / 100 + Math.cos(t * .1 + n.y) * .22 }); const positions = new Map(graph.nodes.map(n => [n.id, point(n)])); const neighbors = active ? new Set(graph.edges.flatMap(e => e.from === active ? [e.to] : e.to === active ? [e.from] : [])) : null; ctx.lineWidth = .7; graph.edges.forEach(edge => { const a = positions.get(edge.from)!; const b = positions.get(edge.to)!; const dim = active && active !== edge.from && active !== edge.to && !neighbors?.has(edge.from) && !neighbors?.has(edge.to); ctx.strokeStyle = edge.emphasis ? 'rgba(30,30,30,.24)' : dim ? 'rgba(60,60,60,.025)' : 'rgba(60,60,60,.09)'; ctx.beginPath(); ctx.moveTo(a.x, a.y); ctx.lineTo(b.x, b.y); ctx.stroke() }); graph.nodes.forEach(node => { const p = positions.get(node.id)!; const selected = active === node.id; const dim = active && !selected && !neighbors?.has(node.id); const r = node.anchor ? 4.2 : 1.35; ctx.globalAlpha = dim ? .12 : 1; ctx.fillStyle = colors[node.kind]; ctx.beginPath(); ctx.arc(p.x, p.y, selected ? r + 1.5 : r, 0, Math.PI * 2); ctx.fill(); if (node.anchor) { ctx.strokeStyle = selected ? '#111' : 'rgba(70,70,70,.25)'; ctx.lineWidth = 1; ctx.beginPath(); ctx.arc(p.x, p.y, r + 3, 0, Math.PI * 2); ctx.stroke() } if (node.anchor || selected) { ctx.font = '10px Arial'; ctx.fillStyle = '#5f5f5f'; ctx.fillText(node.label, p.x + r + 7, p.y + 3) } }); ctx.globalAlpha = 1; if (!reduced) raf = requestAnimationFrame(draw) }; resize(); const observer = new ResizeObserver(resize); observer.observe(wrap); draw(start); return () => { cancelAnimationFrame(raf); observer.disconnect() } }, [active, graph, reduced])
  const select = (event: React.PointerEvent<HTMLCanvasElement>) => { if (!interactive) return; const rect = event.currentTarget.getBoundingClientRect(); const x = event.clientX - rect.left; const y = event.clientY - rect.top; const node = graph.nodes.find(n => { const nx = rect.width * n.x / 100; const ny = rect.height * n.y / 100; return Math.hypot(nx - x, ny - y) < (n.anchor ? 14 : 8) }); setActive(node?.id ?? null) }
  return <div ref={wrapRef} className="network-frame"><canvas ref={canvasRef} className="network-canvas" onPointerDown={select} role="img" aria-label={label} tabIndex={interactive ? 0 : -1} /><span className="network-caption">{label}</span></div>
}

export default Network
